#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Catálogo Fauna Sonora — parte 1: passarinhos e aves grandes.

Cada registro é (nome, científico, grupo, arquivo_de_áudio_no_Commons,
duração_s, arquivo_da_foto_no_Commons, tipo_de_som, habitat, como_produz,
curiosidade). Todos os arquivos foram conferidos um a um na API do
Wikimedia Commons (existência, MIME e duração reais).
"""

GROUPS = {
    "passarinhos": "Passarinhos",
    "aves": "Aves grandes",
    "terrestres": "Mamíferos terrestres",
    "fazenda": "Fazenda",
    "marinhos": "Vida marinha",
    "herpetos": "Anfíbios e répteis",
    "insetos": "Insetos",
}

PASSERINES = [
    ("Sabiá-laranjeira", "Turdus rufiventris", "passarinhos",
     "Turdus rufiventris - Rufous-bellied Thrush XC112745.mp3", 86,
     "Turdus-rufiventris.jpg", "canto",
     "Bordas de mata, cerrado, pomares e jardins de toda a América do Sul.",
     "Siringe (órgão vocal na base da traqueia); canta de poleiro alto, quase sempre ao amanhecer.",
     "É a ave-símbolo do Brasil. O macho repete cada frase do repertório de 2 a 4 vezes e conhece de 10 a 15 estrofes."),

    ("Bem-te-vi", "Pitangus sulphuratus", "passarinhos",
     "Pitangus sulphuratus - Great Kiskadee XC248805.mp3", 10,
     "Great kiskadee (70240).jpg", "chamado territorial",
     "Áreas abertas, beiras de estrada e cidades, do sul dos EUA à Argentina.",
     "Três notas explosivas e metálicas emitidas pela siringe, muitas vezes durante um voo curto.",
     "O nome popular é onomatopeia do grito. Defende o território atacando até carcarás e gaviões maiores que ele."),

    ("Uirapuru-do-amazonas", "Cyphorhinus arada", "passarinhos",
     "Cyphorhinus arada - Musician Wren XC242525.mp3", 20,
     "Cyphorhinus arada arada - Musician wren, Pte. Figueiredo, Amazonas, Brazil.jpg", "canto flautado",
     "Sub-bosque úmido da Amazônia e de florestas da América Central.",
     "Notas longas e flautadas, com duetos do casal ao amanhecer e no fim da tarde.",
     "É o pássaro das lendas caboclas: reza a história que quem escuta seu canto fica encantado e desiste da caça."),

    ("Corruíra", "Troglodytes musculus", "passarinhos",
     "Troglodytes musculus - Southern House Wren, São Paulo, Brazil XC436932.mp3", 49,
     "Southern house wren (Troglodytes musculus) Santiago.jpg", "castoleio",
     "Cercas, telhados, jardins e capoeiras, do Panamá à Argentina.",
     "Repertório raspante e acelerado, com notas imitadas de outras aves e até sons mecânicos.",
     "Com só 12 cm, canta perto de 90 dB a um metro de distância — volume de liquidificador ligado."),

    ("Tico-tico", "Zonotrichia capensis", "passarinhos",
     "Zonotrichia capensis - Rufous-collared Sparrow XC601007.mp3", 98,
     "Rufous-collared sparrow (Zonotrichia capensis costaricensis) 2.jpg", "trilo",
     "Campos, jardins e encostas andinas, do sul do México à Terra do Fogo.",
     "Trilo final descendente produzido na siringe, seguido de notas secas e isoladas.",
     "As populações andinas têm dialetos diferentes: um tico-tico chileno não responde ao chamado de um colombiano."),

    ("Cardeal-da-américa-do-norte", "Cardinalis cardinalis", "passarinhos",
     "Cardinalis cardinalis - Northern Cardinal XC569289.mp3", 198,
     "Male northern cardinal in Central Park (52612).jpg", "assobio",
     "Bosques clareados, pântanos e quintais da América do Norte.",
     "Notas lentas, puras e assobiadas, sempre repetidas de duas a quatro vezes do mesmo poleiro.",
     "Macho e fêmea trocam cantos para combinar a vez na incubação — e a fêmea costuma dar a última palavra."),

    ("Pintassilgo-europeu", "Carduelis carduelis", "passarinhos",
     "Carduelis carduelis - European Goldfinch XC503634.mp3", 8,
     "072 Wild European goldfinch at the Parc Jura vaudois Photo by Giles Laurent.jpg", "chilreado",
     "Campos com cardos, clareiras e pomares da Eurásia; introduzido na Austrália.",
     "Chamados metálicos ‘tilití’ emitidos em bando, quase sempre durante o voo ondulante.",
     "O nome científico vem de carduus: vive das sementes do cardo, que abre com o bico fino."),

    ("Melro-preto", "Turdus merula", "passarinhos",
     "Turdus merula - Common Blackbird XC533751.mp3", 63,
     "Common Blackbird.jpg", "canto",
     "Parques, bosques e jardins da Europa e da Ásia; introduzido na Nova Zelândia.",
     "Flautas graves e variadas, com pausas curtas entre as frases.",
     "Melros de cidade cantam em tom mais alto e até à noite para escapar do ruído do tráfego."),

    ("Rouxinol-comum", "Luscinia megarhynchos", "passarinhos",
     "Luscinia megarhynchos - Common Nightingale XC138451.mp3", 101,
     "Luscinia megarhynchos - Common nightingale - Nachtegaal (cropped).jpg", "canto noturno",
     "Matas ciliares, sarçaais e bosques úmidos da Europa e do norte da África.",
     "Siringe muito musculosa: alterna assobios, estalos e trilos sem repetir a mesma frase duas vezes.",
     "Canta de madrugada e também no escuro, empoleirado no chão. Chega a 320 frases por minuto."),

    ("Pica-pau-de-cabelo-branco", "Dryobates pubescens", "passarinhos",
     "Dryobates pubescens - Downy Woodpecker XC134879.mp3", 140,
     "Dryobates pubescens UL 03.jpg", "chamado e tamborilar",
     "Florestas claras, bosques de galeria e parques suburbanos da América do Norte.",
     "Chamado ‘pik’ nasal na siringe, somado à percussão do bico em madeira oca.",
     "O tamborilar não é voz: é ferramenta de comunicação, e cada indivíduo tem um ritmo reconhecível."),

    ("Beija-flor-de-anna", "Calypte anna", "passarinhos",
     "Calypte anna - Anna's Hummingbird XC153035.mp3", 41,
     "Anna's hummingbird (Calypte anna) male in flight Campbell River.jpg", "canto e ruído de voo",
     "Jardins e bosques do oeste da América do Norte.",
     "Frases agudas e robóticas na siringe; o zumbido é puro batimento de asas, até 50 vezes por segundo.",
     "Na corte, o mergulho de exibição produz estalo sônico com as penas da cauda, perto de 100 dB."),

    ("Andorinha-comum", "Hirundo rustica", "passarinhos",
     "Hirundo rustica - Barn Swallow XC83449.mp3", 19,
     "Rauchschwalbe Hirundo rustica.jpg", "gorjeio de voo",
     "Celeiros, pontes e beiras de rio; migra entre a Europa e a África.",
     "Ráfagas de chilreios emitidos em pleno voo, com trilo final arrastado.",
     "Percorre até 11 000 km por ano entre sítios de nidificação e invernada, voltando ao mesmo ninho."),

    ("Pardal-doméstico", "Passer domesticus", "passarinhos",
     "Passer domesticus - House Sparrow XC86749.mp3", 11,
     "House sparrow male in Prospect Park (53532).jpg", "piado de bando",
     "Centros urbanos do mundo inteiro, exceto florestas densas e desertos.",
     "‘Cheep’ curto e repetitivo; o macho encadeia várias notas ao anunciar o poleiro.",
     "Um dos poucos pássaros que se deram melhor com a urbanização: perdeu o medo e ganhou o mundo."),

    ("Rolinha-dos-ceus", "Columba livia", "passarinhos",
     "Columba livia - Rock Dove XC539061.mp3", 39,
     "Columba livia (Rock Dove, wild), Duncansby Head, Caithness, Scotland 1.jpg", "arrulho",
     "Falésias nativas; hoje praças, cornijas e telhados do mundo inteiro.",
     "O coo sai da parte superior da siringe inflando o terço inicial do esôfago — o papo funciona como caixa de ressonância.",
     "O arrulho tem cinco notas: a primeira anuncia, as do meio pedem atenção e a última confirma o par."),

    ("Codorniz-comum", "Coturnix coturnix", "passarinhos",
     "Coturnix coturnix - Common Quail XC476230.mp3", 15,
     "Coturnix coturnix, Fraunberg, Bayern, Deutschland 1, Ausschnitt.jpg", "canto de território",
     "Trigais, prados e campos de cultivo da Europa, África e Ásia ocidental.",
     "Sequência de três notas silábicas — ‘cot-cot-cotcodiz’ — emitida do chão, escondida entre as espigas.",
     "O canto do macho era usado como isca sonora na caça; hoje é referência para monitorar a qualidade do campo."),
]

BIG_BIRDS = [
    ("Quero-quero", "Vanellus chilensis", "aves",
     "Vanellus Chilensis.ogg", 34,
     "Southern Lapwing - Indaiatuba, SP, BR.jpg", "grito de alarme",
     "Campos abertos, pastagens e gramados de todo o Brasil.",
     "Grito cortado ‘qué-ro-qüê’ emitido com a cabeça erguida e as asas semiabertas; tem vocalizações de alarme específicas para cada predador.",
     "Faz o avestruz-de-pau: finge asa quebrada para afastar predadores do ninho e ataca de bico na altura do olho."),

    ("Seriema", "Cariama cristata", "aves",
     "Cariama cristata call.flac", 31,
     "174 Red-legged seriema in Encontro das Águas State Park Photo by Giles Laurent.jpg", "berrido em dueto",
     "Campos limpos, pastagens e cerrados da América do Sul central.",
     "Berrido grave emitido em dueto pelo casal, muitas vezes com a cabeça apontada para o céu.",
     "Não voa bem, mas corre e salta; e costuma usar cupinzeiros como mirante para cantar."),

    ("Tucano-toco", "Ramphastos toco", "aves",
     "Toco Toucan call (Ramphastos toco).ogg", 11,
     "006 Toco toucan in Encontro das Águas State Park Photo by Giles Laurent.jpg", "gridos roucos",
     "Cerrado, florestas de galeria e bordas de mata da América do Sul.",
     "Crocantes guturais produzidos com a glote; o bico enorme não amplifica som, mas ajuda a dissipar calor.",
     "O som parece o de um sapo grande. Os filhotes fazem um chocalho interno pedindo comida durante semanas."),

    ("Arara-de-fronte-castanha", "Ara severus", "aves",
     "Ara severus - Chestnut-fronted Macaw XC519607.mp3", 19,
     "Ara severus - Guacamaya cariseca - Chestnut-Fronted Macaw (7503884654).jpg", "grito rouco",
     "Florestas, palmeirais e bordas de rio da América Central e do Sul.",
     "Gritos rasgados emitidos pela siringe com a traqueia alongada; usam-nos para manter o bando unido em voo.",
     "É a menor das araras do gênero Ara e uma das poucas que toleram áreas alteradas pelo homem."),

    ("Arara-vermelha", "Ara macao", "aves",
     "Scarlet macaw 01.wav", 16,
     "Scarlet macaw (Ara macao cyanopterus) Copan.jpg", "alarido",
     "Dossel de floresta amazônica e centro-americana, até 500 m.",
     "Gritos metálicos e estridentes que atravessam quilômetros de mata fechada, pois a floresta filtra sons graves.",
     "Vive em casais fixos e alimenta-se de argila de barranco para neutralizar toxinas das sementes."),

    ("Coruja-do-mato", "Strix aluco", "aves",
     "Strix aluco - Tawny Owl XC494801.mp3", 42,
     "Strix aluco 3 (Martin Mecnarowski).jpg", "uivo e chiado",
     "Florestas, parques e cemitéros arborizados da Europa e da Ásia Ocidental.",
     "Assobio grave ‘hu-huu-huu’ do macho, respondido pela fêmea com nota mais alta e aguda.",
     "As penas serrilhadas cortam o ar sem turbulência: voa em silêncio absoluto, abaixo de 1 dB de ruído próprio."),

    ("Coruja-das-torres", "Tyto alba", "aves",
     "Tyto alba - Western Barn Owl XC592539.mp3", 65,
     "Barn Owl, Lancashire.jpg", "grito e cliques das crias",
     "Celeiros, paióis e campos abertos de quase todos os continentes.",
     "O ‘shaar’ estridente sai da siringe; os filhotes fazem estalos de pedido de comida audíveis a dezenas de metros.",
     "O disco facial funciona como antena parabólica e permite localizar uma presa no escuro só pelo som."),

    ("Águia-careca", "Haliaeetus leucocephalus", "aves",
     "Yellowstone sound library - Bald Eagle - 003.mp3", 10,
     "Bald eagle about to fly in Alaska (2016).jpg", "chiados de contato",
     "Lagos, rios e costas com peixes da América do Norte.",
     "Série de assobios curtos e rispidos usados para contato entre o casal e com as crias — nada do rugido cinematográfico.",
     "O grito real lembra mais o de uma gaivota; no cinema é trocado pelo do falcão-gerfalcon por soar mais imponente."),

    ("Falcão-peregrino", "Falco peregrinus", "aves",
     "Halcón peregrino.ogg", 15,
     "Falco peregrinus m Humber Bay Park Toronto.jpg", "akak-akak",
     "Penhascos, arranha-céus e áreas abertas de todo o planeta.",
     "Chamado ‘ak-ak-ak’ rápido emitido perto do ninho para advertir intrusos.",
     "No mergulho de caça passa de 320 km/h — o bicho mais rápido do planeta e o som do ar é audível na câmera lenta."),

    ("Pavão-indiano", "Pavo cristatus", "aves",
     "MalePeacockCall.ogg", 8,
     "Peacock on tree (52077240794).jpg", "berrido e infrasom",
     "Bosques secos e margens de rio do subcontinente indiano; criado em parques do mundo todo.",
     "Berrido metálico ‘may-awe’ e, durante a corte, sons abaixo de 20 Hz que os humanos quase não ouvem.",
     "A fêmea percebe as infrasons a centenas de metros; a cauda é vista, mas é o peito que faz o ruído."),

    ("Galo-doméstico", "Gallus gallus domesticus", "aves",
     "Rooster crowing.ogg", 4,
     "Male and female chicken sitting together.jpg", "cocorocó",
     "Galpões, fazendas e quintais do mundo inteiro.",
     "O canto começa com o animal inflando os sacos aéreos claviculares; o som sai pela siringe com a traqueia em ‘S’.",
     "Cora antes do amanhecer porque a retina é fotossensível: o relógio interno já está ligado horas antes da luz."),

    ("Pato-real", "Anas platyrhynchos", "aves",
     "Anas platyrhynchos - Mallard XC112828.mp3", 17,
     "Anas platyrhynchos male female quadrat.jpg", "quack e assobio",
     "Lagos, represas, lagoas costeiras e parques urbanos do Hemisfério Norte.",
     "O ‘qua’ alto e vibrado da fêmea vem da siringe alongada; o macho tem a traqueia em forma de sino e assobia baixo.",
     "O mito de que o quack não gera eco veio do próprio dorso curvo do bico, que espalha o som para trás."),

    ("Martim-pescador", "Alcedo atthis", "aves",
     "Alcedo atthis - Common Kingfisher XC476785.mp3", 18,
     "Alcedo atthis -England-8 (cropped).jpg", "chilreio telegráfico",
     "Beiras de rio, lagoas e canais de água limpa da Eurásia e do norte da África.",
     "Nota única, aguda e cortante, emitida em voo rente à água, repetida como um apito de trem.",
     "Voa a 40 km/h e mergulha com o mesmo rumo: o cérebro corrige a refração da água em milissegundos."),

    ("Corvo-comum", "Corvus corax", "aves",
     "Corvus corax - Northern Raven XC488951.mp3", 47,
     "Corvus corax clarionensis, Point Reyes National Seashore.jpg", "graus e sons onomatopaicos",
     "Tundras, desertos, montanhas e cidades do Hemisfério Norte.",
     "Vocabulário com mais de 30 emissões: ‘graah’ profundo, cliques, sons de sino e imitações de outros animais.",
     "É um dos poucos animais que usam o som para mentir: emite alarme falso para afastar o rival e roubar a carcaça."),

    ("Pinguim-pequeno", "Eudyptula minor", "aves",
     "20091121 Little Penguin calls at St Kilda Breakwater.ogg", 85,
     "Eudyptula minor Bruny 1.jpg", "latido de reconhecimento",
     "Costas rochosas do sul da Austrália, Tasmânia e Nova Zelândia.",
     "Berrido ‘eek-eek-aahk’ emitido com a cabeça inclinada para trás; o casal reconhece as vozes entre milhares.",
     "É o menor pinguim do mundo (33 cm) e volta para a mesma toca, ao mesmo horário, há décadas na mesma colônia."),
]