# -*- coding: utf-8 -*-
"""Catálogo Fauna Sonora — parte 2: mamíferos, fazenda, mar, herpetos, insetos."""

MAMMALS = [
    ("Leão", "Panthera leo", "terrestres",
     "Lionroar.wav", 43,
     "020 The lion king Snyggve in the Serengeti National Park Photo by Giles Laurent.jpg", "rugido",
     "Savanas e mosaicos de floresta da África Subsaariana; uma pequena população na Índia.",
     "Rugido de baixa frequência que se propaga por até 8 km; a crina escura ajuda a amortecer o impacto nas brigas.",
     "Os leões rugem em coro para demarcar o território, e cada bando reconhece a composição do vizinho pelo som."),

    ("Onça-pintada", "Panthera onca", "terrestres",
     "Jaguar saw.flac", 1,
     "Standing jaguar.jpg", "sawt (contato amigável)",
     "Amazônia, Pantanal, Cerrado e Mata Atlântica, do México à Argentina.",
     "Grunhido nasal curto — o sawt — usado para reconhecimento a curta distância, emitido com a boca entreaberta.",
     "Ao contrário do leão e do tigre, a onça não ruge: o osso hioide é rígido, e o crânio é feito para perfurar casco."),

    ("Tigre", "Panthera tigris", "terrestres",
     "439280 schots angry-tiger.wav", 66,
     "Bengal tiger (Panthera tigris tigris) female 3 crop.jpg", "rugido",
     "Florestas de tigre-de-bengala, taiga siberiana, manguezais de Sundarbans.",
     "Rugido grave acompanhado de infrasom, que atravessa a mata densa sem perder energia.",
     "O tigre também prusten: um grunhido suave de saudação, emitido com a boca fechada, equivalente ao miau dos gatos."),

    ("Lobo-cinzento", "Canis lupus", "terrestres",
     "Wolf howls.ogg", 28,
     "Canis lupus 265b.jpg", "uivo coletivo",
     "Florestas boreais, tundra, montanhas e pradarias do Hemisfério Norte.",
     "Ar forçado pelas pregas vocais com o focinho erguido; o uivo é modulável em pitch para contar quantos são.",
     "A matilha altera as notas de propósito, para dar a impressão de ser maior, e o coro é ouvido a 10 km."),

    ("Coiote", "Canis latrans", "terrestres",
     "Pack of coyotes howling.ogg", 44,
     "2009-Coyote-Yosemite.jpg", "yalos, uivos e latidos",
     "Pradarias, desertos, subúrbios e cidades da América do Norte e Central.",
     "Três repertórios combinados: uivo longo, yowl de agressão e latido curto de alarme.",
     "Um casal pode preencher o território com um coro que parece uma alcateia inteira; é o que assusta vizinhos."),

    ("Cachorro", "Canis lupus familiaris", "terrestres",
     "Barking of a dog.ogg", 3,
     "Huskiesatrest.jpg", "latido",
     "Convívio humano há mais de 15 000 anos, em todo o planeta.",
     "Latido é variação da frequência das pregas vocais, muitas vezes precedido de inspiração forçada — por isso soa áspero.",
     "Cachorros aprenderam a latir para humanos: latem mais que lobos, mesmo criados juntos, e usam o som para pedir."),

    ("Gato", "Felis catus", "terrestres",
     "Felis silvestris catus meows.ogg", 11,
     "Cat August 2010-4.jpg", "miau e ronronar",
     "Ambientes domésticos em todos os continentes habitados.",
     "O miau é modulado de propósito para imitar o choro de um bebê humano; o ronronar vem de contrações da laringe a 25 Hz.",
     "Adultos quase não miam entre si: o repertório foi desenvolvido para falar conosco."),

    ("Raposa-vermelha", "Vulpes vulpes", "terrestres",
     "FuchsSchreit.mp3", 39,
     "Portrait of a red fox in Rautas fjällurskog (cropped).jpg", "uivo e ‘gobble’",
     "Do ártico às cidades: tundra, florestas, campos e subúrbios do Hemisfério Norte.",
     "Grito ascendente de território (the scream) e um ‘gobble’ de disputa emitido por machos rivais.",
     "Usa o campo sonoro para caçar: consegue localizar uma presa sob 40 cm de neve pelo som dos passos."),

    ("Elefante-africano", "Loxodonta africana", "terrestres",
     "Bee-Threat-Elicits-Alarm-Call-in-African-Elephants-pone.0010346.s001.ogg", 5,
     "178 Male African bush elephant in Etosha National Park Photo by Giles Laurent.jpg", "ronronar e infrarrugido",
     "Savanas, bosques e desertos da África Subsaariana.",
     "Rumbles abaixo de 20 Hz produzidos na laringe; viajam quilômetros pelo solo e são sentidos pelas patas e pela tromba.",
     "Este registro é um alarme-grito provocado por abelhas: manadas que já sofreram picadas emitem o som e fogem."),

    ("Bugio", "Alouatta sp.", "terrestres",
     "Howler monkey.ogg", 25,
     "Mantled howler monkey and baby (81337)2.jpg", "rugido de território",
     "Mata Atlântica, florestas da América Central e do Sul, dossel contínuo.",
     "O ar passa por um osso hioide enorme, que funciona como caixa de ressonância dentro do peito.",
     "É um dos animais mais altos da floresta: chega a 114 dB e é ouvido a 5 km, o que evita brigas físicas."),

    ("Urso-pardo", "Ursus arctos", "terrestres",
     "Yellowstone sound library - Grizzly Bears Roar - 001.mp3", 11,
     "2010-kodiak-bear-1.jpg", "grunhido e huff",
     "Florestas, montanhas e tundra da América do Norte, Europa e Ásia.",
     "Grunhidos, estalos de lábios e huffing rítmico; crias fazem um murmúrio contínuo enquanto mamam.",
     "O huff-huff é normalmente aviso de desconforto, não ataque: é o urso pedindo distância antes de decidir."),

    ("Esquilo-cinzento", "Sciurus carolinensis", "terrestres",
     "Grey Squirrel (Sciurus carolinensis) (W1CDR0001470 BD12).ogg", 66,
     "EasternGraySquirrel GAm.jpg", "chuck e trillo",
     "Florestas de folha caduca e parques; introduzido na Europa.",
     "Alarme ‘chuck-chuck’ seco e trillo de submissão emitido com a cauda erguida, sempre com saltos no galho.",
     "Finge que enterra nozes para enganar os observadores — e o som do enterro fazemos de propósito para plateia."),

    ("Morcego", "Eptesicus fuscus", "terrestres",
     "Bat feeding buzz.wav", 7,
     "Big-eared-townsend-fledermaus.jpg", "ecolocalização",
     "Cavernas, florestas, pontes e bairros de todo o mundo, exceto regiões polares.",
     "Pulsos ultrassônicos emitidos pela laringe, 200 por segundo durante a perseguição (o feeding buzz).",
     "O arquivo é a gravação transposta para a faixa audível: no ar, os cliques ficam acima de 20 kHz."),
]

FARM = [
    ("Vaca", "Bos taurus", "fazenda",
     "Single Cow Moo.ogg", 4,
     "Cow (Fleckvieh breed) Oeschinensee Slaunger 2009-07-07.jpg", "mugido",
     "Pastagens, currais e fazendas leiteiras do mundo inteiro.",
     "Mugido grave sustentado pela vibração das pregas vocais com pouca passagem de ar — por isso o som parece vindo do peito.",
     "Vacas chamam as crias pelo mugido individual e respondem ao próprio nome quando a ordenha é sempre no mesmo horário."),

    ("Cavalo", "Equus caballus", "fazenda",
     "Wiehern.ogg", 2,
     "Nokota Horses cropped.jpg", "relincho",
     "Campos, estrebarias e rebanhos selvagens (mustangs) de áreas abertas.",
     "Relincho agudo emitido com as narinas semi-fechadas; o nicker grave e roçado é o som de reconhecimento social.",
     "Cavalos distinguem pelo relincho quem são seus companheiros de baia e quem é estranho chegando."),

    ("Burro", "Equus asinus", "fazenda",
     "157763 felix-blume a-donkey-is-braying-in-his-enclosure-in-south-of-france.wav", 22,
     "Donkey in Clovelly, North Devon, England.jpg", "zurrar",
     "Origem no asno-selvagem africano; hoje áreas áridas e trabalho rural no mundo todo.",
     "O zurrar dura até 3 segundos por fase e usa duas emissões seguidas: uma alta, expirada, e outra baixa, inspirada.",
     "O burro usa o zurro para chamar o grupo em tempestade de areia, quando a visão não serve: é mais eficiente que o relincho."),

    ("Ovelha", "Ovis aries", "fazenda",
     "Sheep bleating.ogg", 8,
     "Flock of sheep.jpg", "balido",
     "Campos, montanhas e sistemas extensivos em todos os continentes.",
     "Balido nasal de contato entre mãe e cordeiro, modulado pelo comprimento do trato vocal.",
     "Ovelhas reconhecem até 50 indivíduos pela voz por anos e lembram de quem as tratou bem."),

    ("Cabra", "Capra hircus", "fazenda",
     "Herd of goats bleating.ogg", 43,
     "Hausziege 04.jpg", "berro",
     "Terrenos rochosos, montanhas e sistemas familiares de criação; uma das primeiras espécies domesticadas.",
     "Berro grave e vibrado que o bode emite durante a estação reprodutiva, sem parar, dia e noite.",
     "Cabras respondem ao próprio nome e usam o berro em três variações: contato, angústia e protesto."),

    ("Porco", "Sus scrofa domesticus", "fazenda",
     "Wa Wanlin aclevaedje pourceas (I).ogg", 291,
     "Pig farm Vampula 1.jpg", "grunhido e guincho",
     "Chiqueiros, áreas alagadiças e matas; o javali é o ancestral selvagem.",
     "Grunhidos de contato com frequência modulada por sacos laríngeos; leitões emitem guinchos agudos ao disputar a teta.",
     "Porcos têm mais de 20 vocalizações distintas e usam sons graves para localizar comida no escuro do chiqueiro."),
]

SEA = [
    ("Baleia-jubarte", "Megaptera novaeangliae", "marinhos",
     "Humpback whale wheezeblow.ogg", 61,
     "Humpback whale breaching off Cabo San Lucas.jpg", "canto",
     "Oceanos polares e tropicais; migra até 8 000 km por ano.",
     "Sem cordas vocais humanas: o ar circula entre sacos nasal e laríngeo, e por isso ela canta sem precisar inspirar.",
     "Os machos de uma mesma bacia cantam exatamente a mesma música, que evolui temporada a temporada."),

    ("Orca", "Orcinus orca", "marinhos",
     "Killer whale.ogg", 30,
     "Killerwhales jumping.jpg", "chamado de reconhecimento",
     "Todos os oceanos, do Ártico à Antártida; caça em grupos familiares.",
     "Ar comprimido entre os lábios fônicos no topo da cabeça, independente da respiração.",
     "Cada família tem dialeto próprio: a cria aprende o sotaque da mãe e o conserva a vida inteira."),

    ("Elefante-marinho-do-sul", "Mirounga leonina", "marinhos",
     "AudioElleSeals.oga", 8,
     "See elefanten edit.jpg", "rugido de disputa",
     "Praias da Patagônia, Geórgia do Sul e arquipélagos subantárticos.",
     "O pescoço inflável, que parece uma probóscide, funciona como ressonador e amplifica o latido grave.",
     "Durante a disputa, os machos pulsam o som a mais de 120 dB e conseguem ficar semanas sem beber água."),
]

HERPS = [
    ("Sapo-comum", "Bufo bufo", "herpetos",
     "Bufo bufo call1.ogg", 17,
     "Common Toad Cornwall.jpeg", "grunhido de acasalamento",
     "Charcos, bosques e jardins da Europa e do norte da Ásia.",
     "Empurra ar pelos pulmões enquanto a pele do topo da cabeça vibra; o gênero Bufo não tem saco vocal.",
     "Na migração reprodutiva, machos se agarram a qualquer coisa que pareça fêmea, inclusive paus e outros machos."),

    ("Perereca-europeia", "Hyla arborea", "herpetos",
     "XN Hyla arborea 01.ogg", 27,
     "European tree frog (Hyla arborea) on hemp-agrimony (Eupatorium cannabinum).jpg", "coro noturno",
     "Vinhedos, salgueiros e lagoas da Europa; dorme de dia em folhas.",
     "Dois sacos vocais laterais, inflados como bolhas, amplificam o ‘é-é-é’ a centenas de metros.",
     "O coro de pererecas passa de 90 dB — e há registros de gravações do canto delas feitas em disco desde 1911."),

    ("Rã-verde", "Pelophylax ridibundus", "herpetos",
     "Marsh frog (Pelophylax ridibundus) call.ogg", 23,
     "Marsh frog (Pelophylax ridibundus).jpg", "croc-croc",
     "Lagos, pântanos e canais da Eurásia; vive quase sempre na água.",
     "Sacos vocais redondos e esbranquiçados nos cantos da boca, inflados enquanto a rã fica submersa.",
     "É uma das maiores rãs da Europa, com até 14 cm, e salta mais de um metro a partir da posição de espera."),

    ("Jacaré-americano", "Alligator mississippiensis", "herpetos",
     "Alligatorbellow1.ogg", 24,
     "American Alligator.jpg", "bramido com infrasom",
     "Pântanos, rios e lagos do sudeste dos Estados Unidos.",
     "Com a glote fechada, o ar vibra e produz um bramido grave cheio de infrasom.",
     "No auge da estação o bramido é tão intenso que a água sobre as costas do animal salta em gotas."),

    ("Cascavel-diamante", "Crotalus atrox", "herpetos",
     "Rattlesnake.ogg", 15,
     "(Westliche Diamantklapperschlange) Crotalus atrox.jpg", "chocalho",
     "Desertos, caatingas e áreas rochosas do México e do sudoeste dos EUA.",
     "Não vem da boca: são anéis córneos ocos na cauda vibrando em frequência que os mamíferos percebem muito bem.",
     "Cada muda de pele acrescenta um anel, e os anéis podem se soltar: por isso o chocalho não mede a idade."),
]

BUGS = [
    ("Cigada-dos-campos", "Neotibicen sp.", "insetos",
     "Florida Cicada Song.ogg", 86,
     "Cicada - Neotibicen linnei, Woodbridge, Virginia.jpg", "zumbido de timbal",
     "Copas de árvores decíduas da América do Norte.",
     "Músculos abdominais curvam e relaxam dois timbais de quitina centenas de vezes por segundo; o abdômen vazio é a câmara de ressonância.",
     "Passa de 95 dB. Cigadas periódicas emergem em ciclos de 13 ou 17 anos, números primos que dificultam a vida dos predadores."),

    ("Grilo-campônio", "Gryllus campestris", "insetos",
     "Gryllus campestris - sound.ogg", 32,
     "Gryllus campestris 3.jpg", "estridulação",
     "Clareiras secas, muros e campos ensolarados da Europa central.",
     "A lima de uma élitro é raspada na outra por um músculo; a forma das asas faz o papel de corneta.",
     "A frequência sobe com a temperatura ambiente: contando os chirps em 15 segundos e somando 5, estima-se a temperatura."),

    ("Mamangava", "Bombus terrestris", "insetos",
     "Bombus buzz.ogg", 11,
     "Bombus lapidarius - Melilotus officinalis - Tallinn.jpg", "zumbido de voo",
     "Prados, hortas e bordas de campo da Europa; também usada em estufas.",
     "Asas batendo cerca de 130 vezes por segundo, com o corpo peludo servindo de ressonador.",
     "Pratica polinização por vibração: emite um zumbido em torno de 400 Hz que derruba o pólen da flor."),

    ("Gafanhoto-migratório", "Locusta migratoria", "insetos",
     "Grasshoppers.ogg", 17,
     "Locusta-migratoria-wanderheuschrecke.jpg", "crepitar de pernas",
     "Estepes, lavouras e dunas de todos os continentes, exceto a América.",
     "O fêmur é raspado contra a série de cristas da asa; em bando, os estalos se fundem num chiado contínuo.",
     "Quando a população cresce, o inseto muda de cor, de apetite e de comportamento: nasce a praga."),
]
